// Copyright (C) 2026 Kerem Gok
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Signing what an ACME server reads, and naming the key that signed it.
//!
//! Every request in an ACME order except the first is a JWS: a signed
//! envelope carrying the request body (RFC 8555 section 6). Nothing here
//! opens a socket, so what is signed and how the account is named are both
//! measurable without a server.
//!
//! # Why the key never leaves this module as text
//!
//! The account key is what an ACME server recognises the account by. Anybody
//! holding it can revoke every certificate the account ever obtained, so it is
//! read from the store, used, and dropped. It is never formatted, never
//! logged, and never carried in an error.

use openssl::bn::{BigNum, BigNumContext};
use openssl::ecdsa::EcdsaSig;
use openssl::hash::{MessageDigest, hash};
use openssl::pkey::{PKey, Private};

use crate::error::{Failure, Reason};

/// The curve an account key uses.
///
/// One algorithm rather than a choice: every ACME server supports ES256, the
/// key is generated by this product and never imported, and an operator has
/// no reason to hold an opinion about it.
pub const CURVE: openssl::nid::Nid = openssl::nid::Nid::X9_62_PRIME256V1;

/// How many bytes one P-256 coordinate takes.
///
/// Fixed width matters: a coordinate that happens to start with a zero byte
/// must still be sent as 32 bytes, or the signature and the thumbprint are
/// computed over different bytes than the server computes them over.
const COORDINATE: i32 = 32;

/// The key an ACME account is recognised by.
///
/// Named here so a caller can hold one without depending on the TLS library
/// itself. Nothing outside this crate has any reason to know what it is made
/// of.
pub type Account = PKey<Private>;

/// Reads an account key that was stored.
///
/// # Errors
///
/// Returns [`Reason::Crypto`] when the material does not open as a key.
pub fn account_from_pem(pem: &[u8]) -> Result<Account, Failure> {
    // The callback answers with no passphrase rather than letting OpenSSL ask
    // for one: this runs with no terminal, and the default would wait forever
    // on a prompt nobody sees.
    PKey::private_key_from_pem_callback(pem, |_| Ok(0)).map_err(|error| {
        Failure::new(
            Reason::Crypto,
            format!("the stored account key does not open: {error}"),
        )
    })
}

/// Writes an account key out for the store to seal.
///
/// # Errors
///
/// Returns [`Reason::Crypto`] when the key cannot be written.
pub fn account_to_pem(key: &Account) -> Result<Vec<u8>, Failure> {
    key.private_key_to_pem_pkcs8().map_err(|error| {
        Failure::new(
            Reason::Crypto,
            format!("the account key does not write out: {error}"),
        )
    })
}

/// Generates an account key.
///
/// # Errors
///
/// Returns [`Reason::Crypto`] when the library cannot produce a key.
pub fn account_key() -> Result<PKey<Private>, Failure> {
    let group = openssl::ec::EcGroup::from_curve_name(CURVE)
        .map_err(|error| Failure::new(Reason::Crypto, format!("no P-256 group: {error}")))?;
    let key = openssl::ec::EcKey::generate(&group)
        .map_err(|error| Failure::new(Reason::Crypto, format!("no account key: {error}")))?;
    PKey::from_ec_key(key)
        .map_err(|error| Failure::new(Reason::Crypto, format!("the key does not wrap: {error}")))
}

/// Encodes bytes the way JOSE does: base64 with a URL safe alphabet and no
/// padding.
#[must_use]
pub fn base64url(bytes: &[u8]) -> String {
    let standard = openssl::base64::encode_block(bytes);
    standard
        .trim_end_matches('=')
        .chars()
        .map(|character| match character {
            '+' => '-',
            '/' => '_',
            other => other,
        })
        .collect()
}

/// The public half of an account key, as a JSON Web Key.
///
/// The fields are written in lexicographic order and with no whitespace,
/// because the thumbprint is the hash of exactly these bytes (RFC 7638). A
/// pretty printed copy would hash to something the server never computes.
///
/// # Errors
///
/// Returns [`Reason::Crypto`] when the key's coordinates cannot be read.
pub fn jwk(key: &PKey<Private>) -> Result<String, Failure> {
    let ec = key
        .ec_key()
        .map_err(|error| Failure::new(Reason::Crypto, format!("not an EC key: {error}")))?;
    let mut context = BigNumContext::new()
        .map_err(|error| Failure::new(Reason::Crypto, format!("no context: {error}")))?;
    let mut x = BigNum::new()
        .map_err(|error| Failure::new(Reason::Crypto, format!("no number: {error}")))?;
    let mut y = BigNum::new()
        .map_err(|error| Failure::new(Reason::Crypto, format!("no number: {error}")))?;
    ec.public_key()
        .affine_coordinates_gfp(ec.group(), &mut x, &mut y, &mut context)
        .map_err(|error| {
            Failure::new(
                Reason::Crypto,
                format!("the public point does not read: {error}"),
            )
        })?;

    let x = x
        .to_vec_padded(COORDINATE)
        .map_err(|error| Failure::new(Reason::Crypto, format!("x does not fit: {error}")))?;
    let y = y
        .to_vec_padded(COORDINATE)
        .map_err(|error| Failure::new(Reason::Crypto, format!("y does not fit: {error}")))?;

    Ok(format!(
        r#"{{"crv":"P-256","kty":"EC","x":"{}","y":"{}"}}"#,
        base64url(&x),
        base64url(&y)
    ))
}

/// The account key's thumbprint, which is half of every challenge answer.
///
/// # Errors
///
/// Returns [`Reason::Crypto`] when the key or the digest cannot be computed.
pub fn thumbprint(key: &PKey<Private>) -> Result<String, Failure> {
    let jwk = jwk(key)?;
    let digest = hash(MessageDigest::sha256(), jwk.as_bytes())
        .map_err(|error| Failure::new(Reason::Crypto, format!("no digest: {error}")))?;
    Ok(base64url(&digest))
}

/// What a challenge has to be answered with.
///
/// The token alone would be answerable by anybody who saw it in flight. Tied
/// to the account key's thumbprint, only the holder of that key can produce
/// the answer (RFC 8555 section 8.1).
#[must_use]
pub fn key_authorization(token: &str, thumbprint: &str) -> String {
    format!("{token}.{thumbprint}")
}

/// How the account is named in a signed request.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Identify {
    /// Carry the whole public key. Used for the request that creates the
    /// account, because the server does not know it yet.
    Key,
    /// Carry the account URL. Used for everything after that, because the
    /// server can look the key up and the envelope stays smaller.
    Account,
}

/// Wraps a request body in a signed envelope.
///
/// `payload` being `None` is POST-as-GET: a request that reads a resource but
/// still has to be signed, which is how ACME reads anything private.
///
/// # Errors
///
/// Returns [`Reason::Crypto`] when the key cannot sign, and
/// [`Reason::Protocol`] when the account URL is needed and missing.
pub fn sign(
    key: &PKey<Private>,
    identify: Identify,
    account: Option<&str>,
    url: &str,
    nonce: &str,
    payload: Option<&str>,
) -> Result<String, Failure> {
    let header = match identify {
        Identify::Key => format!(
            r#"{{"alg":"ES256","jwk":{},"nonce":"{}","url":"{}"}}"#,
            jwk(key)?,
            escape(nonce),
            escape(url)
        ),
        Identify::Account => {
            let account = account.ok_or_else(|| {
                Failure::new(
                    Reason::Protocol,
                    "the server named no account to sign as".to_owned(),
                )
            })?;
            format!(
                r#"{{"alg":"ES256","kid":"{}","nonce":"{}","url":"{}"}}"#,
                escape(account),
                escape(nonce),
                escape(url)
            )
        }
    };

    let protected = base64url(header.as_bytes());
    // An empty string, not an absent field: POST-as-GET signs over an empty
    // payload and the server checks the same two parts either way.
    let body = base64url(payload.unwrap_or("").as_bytes());
    let signature = raw_signature(key, format!("{protected}.{body}").as_bytes())?;

    Ok(format!(
        r#"{{"protected":"{protected}","payload":"{body}","signature":"{signature}"}}"#
    ))
}

/// Signs bytes and returns the signature the way JOSE wants it.
///
/// OpenSSL produces a DER structure holding two numbers. ES256 is the two
/// numbers themselves, each padded to 32 bytes. Sending the DER instead is
/// accepted by nothing and fails as a bad signature, which reads like a wrong
/// key.
fn raw_signature(key: &PKey<Private>, message: &[u8]) -> Result<String, Failure> {
    let ec = key
        .ec_key()
        .map_err(|error| Failure::new(Reason::Crypto, format!("not an EC key: {error}")))?;
    let digest = hash(MessageDigest::sha256(), message)
        .map_err(|error| Failure::new(Reason::Crypto, format!("no digest: {error}")))?;
    let signature = EcdsaSig::sign(&digest, &ec)
        .map_err(|error| Failure::new(Reason::Crypto, format!("no signature: {error}")))?;

    let mut bytes = signature
        .r()
        .to_vec_padded(COORDINATE)
        .map_err(|error| Failure::new(Reason::Crypto, format!("r does not fit: {error}")))?;
    bytes.extend(
        signature
            .s()
            .to_vec_padded(COORDINATE)
            .map_err(|error| Failure::new(Reason::Crypto, format!("s does not fit: {error}")))?,
    );
    Ok(base64url(&bytes))
}

/// Makes a value safe to place inside a JSON string.
///
/// The values that pass through here are URLs and nonces the server chose, so
/// none of them should carry a quote or a backslash. Escaping them anyway is
/// what stops a server, or anybody able to answer as one, from writing extra
/// fields into a header this product signs.
fn escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for character in value.chars() {
        match character {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            other if (other as u32) < 0x20 => {
                out.push_str(&format!("\\u{:04x}", other as u32));
            }
            other => out.push(other),
        }
    }
    out
}
